-- V1__baseline.sql
-- Baseline generated from the LIVE database schema (pg_dump --schema-only at the
-- adoption of Flyway; see docs/optimization-plan.md §3). This is exactly what
-- Hibernate ddl-auto:update had produced incrementally since the project started;
-- it is checked in as-is so existing and fresh databases converge to one schema.
-- From here on, schema changes are forward-only migrations; Hibernate runs with
-- ddl-auto:validate and no longer writes DDL.

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: px75_custom_screen; Type: TABLE
--

CREATE TABLE public.px75_custom_screen (
    custom_screen_id bigint NOT NULL,
    design text NOT NULL,
    duration_seconds integer NOT NULL,
    name character varying(64) NOT NULL,
    shared boolean NOT NULL,
    thumbnail text,
    updated_at timestamp(6) with time zone NOT NULL,
    user_id bigint NOT NULL
);

--
-- Name: px75_custom_screen_custom_screen_id_seq; Type: SEQUENCE (identity)
--

ALTER TABLE public.px75_custom_screen ALTER COLUMN custom_screen_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.px75_custom_screen_custom_screen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: px75_panel; Type: TABLE
--

CREATE TABLE public.px75_panel (
    panel_id bigint NOT NULL,
    client_mac character varying(17) NOT NULL,
    name character varying(255) NOT NULL,
    panel_type character varying(255) NOT NULL,
    serial character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT px75_panel_panel_type_check CHECK (((panel_type)::text = 'P_64_X_32'::text))
);

--
-- Name: px75_panel_config; Type: TABLE
--

CREATE TABLE public.px75_panel_config (
    panel_id bigint NOT NULL,
    screens_config jsonb
);

--
-- Name: px75_panel_panel_id_seq; Type: SEQUENCE (identity)
--

ALTER TABLE public.px75_panel ALTER COLUMN panel_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.px75_panel_panel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: px75_roles; Type: TABLE
--

CREATE TABLE public.px75_roles (
    user_id bigint NOT NULL,
    role character varying(255),
    CONSTRAINT px75_roles_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying, 'MODERATOR'::character varying])::text[])))
);

--
-- Name: px75_spotify_connection; Type: TABLE
--

CREATE TABLE public.px75_spotify_connection (
    spotify_connection_id bigint NOT NULL,
    connection_key character varying(32) NOT NULL,
    display_name character varying(128) NOT NULL,
    refresh_token text NOT NULL,
    spotify_user_id character varying(64) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

--
-- Name: px75_spotify_connection_spotify_connection_id_seq; Type: SEQUENCE (identity)
--

ALTER TABLE public.px75_spotify_connection ALTER COLUMN spotify_connection_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.px75_spotify_connection_spotify_connection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: px75_users; Type: TABLE
--

CREATE TABLE public.px75_users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    username character varying(255) NOT NULL
);

--
-- Name: px75_users_id_seq; Type: SEQUENCE (identity)
--

ALTER TABLE public.px75_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.px75_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: primary key constraints
--

ALTER TABLE ONLY public.px75_custom_screen
    ADD CONSTRAINT px75_custom_screen_pkey PRIMARY KEY (custom_screen_id);

ALTER TABLE ONLY public.px75_panel_config
    ADD CONSTRAINT px75_panel_config_pkey PRIMARY KEY (panel_id);

ALTER TABLE ONLY public.px75_panel
    ADD CONSTRAINT px75_panel_pkey PRIMARY KEY (panel_id);

ALTER TABLE ONLY public.px75_spotify_connection
    ADD CONSTRAINT px75_spotify_connection_pkey PRIMARY KEY (spotify_connection_id);

ALTER TABLE ONLY public.px75_users
    ADD CONSTRAINT px75_users_pkey PRIMARY KEY (id);

--
-- Name: unique constraints
--

ALTER TABLE ONLY public.px75_users
    ADD CONSTRAINT uk1jjp8b8kdkirce9badq8jyvwh UNIQUE (email);

ALTER TABLE ONLY public.px75_users
    ADD CONSTRAINT uk6gevr04mi3jcui9v6ppf0gk4h UNIQUE (username);

ALTER TABLE ONLY public.px75_spotify_connection
    ADD CONSTRAINT ukifluil9oaffn0km4vm7swgysq UNIQUE (connection_key);

--
-- Name: foreign key constraints
--

ALTER TABLE ONLY public.px75_roles
    ADD CONSTRAINT fkmtwpc8dg906pbak5jc7wbp3f8 FOREIGN KEY (user_id) REFERENCES public.px75_users(id);
